-- Per-admin read state for actionable notifications. Keys are generated by
-- the server from the current unresolved action instance.
CREATE TABLE IF NOT EXISTS admin_notification_reads (
    user_id INT NOT NULL,
    notification_key VARCHAR(191) NOT NULL,
    read_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, notification_key),
    KEY idx_admin_notification_reads_key (notification_key),
    CONSTRAINT fk_admin_notification_reads_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
