<?php
require_once __DIR__ . '/../../includes/session_init.php';
header('Content-Type: application/json');

require_once __DIR__ . '/../../config/db_connect.php';
require_once __DIR__ . '/../../includes/backup_helper.php';
require_once __DIR__ . '/../../includes/request_context.php';

// Auth check
if (!isset($_SESSION['logged_in']) || $_SESSION['role'] !== 'admin') {
    echo json_encode(['success' => false, 'error' => 'Unauthorized access.']);
    exit();
}

// CSRF check
if (empty($_POST['csrf_token']) || !hash_equals($_SESSION['csrf_token'], $_POST['csrf_token'])) {
    echo json_encode(['success' => false, 'error' => 'Invalid security token.']);
    exit();
}

$ip = request_client_ip();

// Check if file was uploaded
if (!isset($_FILES['sql_file']) || $_FILES['sql_file']['error'] !== UPLOAD_ERR_OK) {
    echo json_encode(['success' => false, 'error' => 'No file uploaded or upload error.']);
    exit();
}

$tmpPath = $_FILES['sql_file']['tmp_name'];
$originalName = basename($_FILES['sql_file']['name']);
$fileSize = $_FILES['sql_file']['size'];

if (!str_ends_with(strtolower($originalName), '.sql')) {
    echo json_encode(['success' => false, 'error' => 'Invalid file type. Only .sql files are allowed.']);
    exit();
}
if ($fileSize <= 0 || $fileSize > BackupHelper::maxBackupBytes()) {
    echo json_encode(['success' => false, 'error' => 'Backup exceeds the configured maximum size.']);
    exit();
}

// Security Check: Verify HMAC Signature BEFORE accepting the upload!
$sqlContent = file_get_contents($tmpPath);
if (empty($sqlContent)) {
    echo json_encode(['success' => false, 'error' => 'File is empty.']);
    exit();
}

$lines = explode("\n", $sqlContent, 2);
if (count($lines) < 2) {
    echo json_encode(['success' => false, 'error' => 'Invalid backup format (Missing signature).']);
    exit();
}

$firstLine = $lines[0];
$restOfContent = $lines[1];

if (strpos($firstLine, '-- Signature: ') !== 0) {
    echo json_encode(['success' => false, 'error' => 'File rejected: Cryptographic signature missing. This file was not generated by Sevilla360 or is an older version.']);
    exit();
}

$providedSignature = trim(substr($firstLine, 14));
$appKey = BackupHelper::getSigningKey();
if ($appKey === null) {
    echo json_encode(['success' => false, 'error' => 'Backup signing is unavailable: configure a strong APP_KEY (at least 32 randomly generated characters).']);
    exit();
}
$expectedSignature = hash_hmac('sha256', $restOfContent, $appKey);

if (!hash_equals($expectedSignature, $providedSignature)) {
    // Audit log the tamper attempt!
    $adminId = $_SESSION['user_id'];
    $auditStmt = $conn->prepare("INSERT INTO audit_logs (user_id, module, action, ip_address) VALUES (?, 'Backup & Recovery', 'Attempted to upload tampered backup file', ?)");
    $auditStmt->bind_param("is", $adminId, $ip);
    $auditStmt->execute();

    echo json_encode(['success' => false, 'error' => 'Security Alert: File rejected! The cryptographic signature does not match. The file has been tampered with or corrupted.']);
    exit();
}

// File is authentic! Move it to storage
try { $backupDir = BackupHelper::resolveBackupDir(true); }
catch (Throwable $e) {
    error_log('Backup import storage resolution failed: ' . get_class($e));
    $audit = $conn->prepare("INSERT INTO audit_logs (user_id, module, action, ip_address) VALUES (?, 'Backup & Recovery', 'Backup import storage resolution failed', ?)");
    if ($audit) { $adminId = (int)($_SESSION['user_id'] ?? 0); $audit->bind_param('is', $adminId, $ip); $audit->execute(); }
    echo json_encode(['success' => false, 'error' => 'Backup storage is unavailable.']);
    exit;
}

$timestamp = date('Y-m-d_H-i-s');
$filename = "sevilla360_imported_{$timestamp}_" . bin2hex(random_bytes(4)) . ".sql";
$destination = BackupHelper::backupFilePath($filename, false);

if (move_uploaded_file($tmpPath, $destination)) {
    
    // Insert into database
    $adminId = $_SESSION['user_id'];
    $stmt = $conn->prepare("INSERT INTO backups (filename, file_size, created_by) VALUES (?, ?, ?)");
    $stmt->bind_param("sii", $filename, $fileSize, $adminId);
    
    if ($stmt->execute()) {
        // Log to audit
        $auditStmt = $conn->prepare("INSERT INTO audit_logs (user_id, module, action, ip_address) VALUES (?, 'Backup & Recovery', ?, ?)");
        $details = "Imported authenticated backup file: {$filename}";
        $auditStmt->bind_param("iss", $adminId, $details, $ip);
        $auditStmt->execute();

        echo json_encode(['success' => true, 'message' => 'Backup imported and verified successfully!']);
    } else {
        unlink($destination); // Clean up if db insert fails
        echo json_encode(['success' => false, 'error' => 'Database error recording imported backup.']);
    }
} else {
    echo json_encode(['success' => false, 'error' => 'Failed to move uploaded file. Check directory permissions.']);
}
?>
