<?php
/** Static contract checks for public venue browsing and guest booking safety. */
declare(strict_types=1);

$root = dirname(__DIR__);
$read = static fn(string $path): string => (string)file_get_contents($root . '/' . $path);
$booking_php = $read('booking.php');
$booking_intent_php = $read('includes/booking_intent.php');
$booking_js = $read('assets/js/booking.js');
$calendar_js = $read('assets/js/calendar.js');
$calendar_timezone_test = $root . '/scripts/test_calendar_timezone.js';
$index_php = $read('index.php');
$index_js = $read('assets/js/index.js');
$featured_reviews_php = $read('actions/public/get_featured_reviews.php');
$lock_dates_php = $read('actions/bookings/lock_dates.php');
$admin_status_php = $read('actions/admin/update_booking_status.php');
$index_css = $read('assets/css/index.css');
$ui_refinement_css = $read('assets/css/ui-refinement.css');
$showroom_php = $read('showroom.php');
$showroom_js = $read('assets/js/showroom.js');
$showroom_css = $read('assets/css/showroom.css');
$support_php = $read('support.php');
$support_css = $read('assets/css/support.css');
$submit_start = strpos($booking_js, 'async submitOnlineBooking()');
$submit_body = $submit_start === false ? '' : substr($booking_js, $submit_start);
$guest_redirect_position = strpos($submit_body, "window.location.href = 'auth.php?destination=booking_resume';");
$customer_lock_position = strpos($submit_body, "if (this.state.activeTabId !== 'event-hall' && !this.state.isDatesLocked)");
$lock_method_start = strpos($booking_js, 'async lockSelectedDates(');
$request_start = strpos($booking_js, 'requestDateConfirmation(startDate, endDate, calendarInstance)');
$request_body = $request_start === false ? '' : substr($booking_js, $request_start);
$restore_start = strpos($booking_js, 'async restoreDraftIfRequested()');
$restore_body = $restore_start === false ? '' : substr($booking_js, $restore_start);
$restore_final_save_position = strpos($restore_body, "this.isRestoringDraft = false;\n            this.saveDraft();");
$invalid_primary_position = strpos($restore_body, 'if (invalidStart || invalidInterior || invalidEnd)');
$invalid_primary_addon_restore_position = $invalid_primary_position === false ? false : strpos($restore_body, 'await this.restoreAddonSelections(draft);', $invalid_primary_position);
$modal_calendar_constructor_count = substr_count($index_js, "new SevillaCalendar('idx-modal-calendar'");
$top_rated_render_start = strpos($index_js, 'const topRatedSection');
$top_rated_render_end = $top_rated_render_start === false ? false : strpos($index_js, 'const updateCarousel', $top_rated_render_start);
$top_rated_render_body = $top_rated_render_start === false || $top_rated_render_end === false ? '' : substr($index_js, $top_rated_render_start, $top_rated_render_end - $top_rated_render_start);
$xss_fixture = '<img src=x onerror=alert(1)> & <special>';
$cancel_position = strpos($admin_status_php, "elseif (\$action === 'cancel')");
$cancel_body = $cancel_position === false ? '' : substr($admin_status_php, $cancel_position, 500);
$checks = [
    'booking page is session-backed and not customer-guarded' => str_contains($booking_php, "require_once 'includes/session_init.php';") && !str_contains($booking_php, "require 'includes/auth_guard.php';"),
    'saved phone lookup is customer-only' => str_contains($booking_php, 'if ($booking_is_customer)') && str_contains($booking_php, '$saved_contact_phone ='),
    'guest lock endpoint remains customer-only' => str_contains($read('actions/bookings/lock_dates.php'), "(\$_SESSION['role'] ?? '') === 'customer'") && str_contains($read('actions/bookings/submit_online.php'), "\$_SESSION['role'] !== 'customer'"),
    'booking draft has a version, ttl, and excludes sensitive fields' => str_contains($booking_js, "sevilla360.booking-draft.v1") && str_contains($booking_js, 'version: 1') && str_contains($booking_js, 'createdAt') && str_contains($booking_js, 'draftTtlMs') && str_contains($booking_js, "? 'Hotel Room'") && !str_contains($booking_js, 'phone:') && !str_contains($booking_js, 'notes:') && !str_contains($booking_js, 'computedTotal:'),
    'booking draft persists add-on selections and saves changes' => str_contains($booking_js, 'addonStartDate') && str_contains($booking_js, 'cateringTier') && str_contains($booking_js, 'roomGroups') && str_contains($booking_js, 'quantityInput.addEventListener') && str_contains($booking_js, 'event-type-others') && substr_count($booking_js, 'this.saveDraft();') >= 8,
    'guest submit redirects before the customer-only lock requirement' => str_contains($submit_body, 'if (!this.state.activeCalendar?.startDate)') && $guest_redirect_position !== false && $customer_lock_position !== false && $guest_redirect_position < $customer_lock_position,
    'guest confirmation never calls the lock endpoint' => $request_start !== false && $lock_method_start !== false && str_contains($request_body, 'const canHold = this.auth.isCustomer && !isEventInquiry') && str_contains($request_body, 'if (!canHold)') && str_contains($request_body, 'this.state.confirmedSelectionKey = this.buildSelectionKey(calendarInstance);') && str_contains($request_body, 'await this.lockSelectedDates(startDate, endDate, calendarInstance, { dateModal, confirmBtn })') && !str_contains($request_body, "lock_dates.php"),
    'auth resume uses matching selection key without a second prompt' => str_contains($restore_body, "typeof draft.confirmedSelectionKey === 'string'") && str_contains($restore_body, 'draft.confirmedSelectionKey === this.buildSelectionKey(calendar)') && str_contains($restore_body, 'await this.lockSelectedDates(calendar.startDate, calendar.endDate, calendar);') && str_contains($restore_body, "if (this.state.activeTabId === 'event-hall')") && str_contains($restore_body, 'calendar.updateDateDisplay();') && str_contains($booking_js, 'buildSelectionKey(calendar = this.state.activeCalendar)'),
    'shared lock method is customer-only and excludes event inquiries' => $lock_method_start !== false && str_contains(substr($booking_js, $lock_method_start), 'if (!this.auth.isCustomer || isEventInquiry || !calendarInstance?.startDate) return false;') && substr_count($booking_js, "fetch('actions/bookings/lock_dates.php'") === 1,
    'selection key is deterministic and invalidated on change or lock failure' => str_contains($booking_js, 'confirmedSelectionKey,') && str_contains($booking_js, 'if (!confirmedSelectionKey) this.state.confirmedSelectionKey = \'\';') && str_contains($booking_js, 'this.state.confirmedSelectionKey = \'\';') && str_contains($booking_js, 'calendarInstance.clearSelectedRange();'),
    'failed resume lock clears the hold claim and refreshes availability' => $lock_method_start !== false && str_contains(substr($booking_js, $lock_method_start), 'this.state.confirmedSelectionKey = \'\';') && str_contains(substr($booking_js, $lock_method_start), 'this.state.isDatesLocked = false;') && str_contains(substr($booking_js, $lock_method_start), 'calendarInstance.fetchBookedDates(') && str_contains(substr($booking_js, $lock_method_start), 'async lockSelectedDates('),
    'restoration scopes payment and checks add-on authority' => str_contains($booking_js, 'item.name === activeContext.activeRadioGroup') && str_contains($booking_js, 'restoreAddonSelections') && str_contains($booking_js, 'updateRoomAvailabilityLabels(startDate, endDate)') && str_contains($booking_js, 'get_room_availability.php'),
    'draft restoration defers writes until all controls are restored' => str_contains($booking_js, 'this.isRestoringDraft = true;') && str_contains($booking_js, 'if (this.isRestoringDraft) return;') && $restore_final_save_position !== false && str_contains($restore_body, 'restoreCatering();') && str_contains($restore_body, 'restoreAv();'),
    'invalid primary dates retain venue options and restore independent add-ons' => $invalid_primary_position !== false && $invalid_primary_addon_restore_position !== false && str_contains(substr($restore_body, $invalid_primary_position), 'restoreCatering();') && str_contains(substr($restore_body, $invalid_primary_position), 'restoreAv();') && str_contains(substr($restore_body, $invalid_primary_position), "calendar.clearSelectedRange();"),
    'checkout redirect clears draft only after server response' => str_contains($booking_js, "if (response[0] === 'CheckoutUrl')") && str_contains($booking_js, "this.clearDraft();\n                window.location.href = response[1];"),
    'modal calendar is created once and category rules reset' => $modal_calendar_constructor_count === 1 && str_contains($index_js, 'modalCalendar.clearSelection()') && str_contains($index_js, 'fixedDurationNights = venue.category === \'Resort Villa\' ? 0 : null') && str_contains($index_js, 'fixedDurationGuard = venue.category === \'Resort Villa\''),
    'homepage cards and modal expose complete category rates' => str_contains($index_php, 'max_nightly_rate') && str_contains($index_php, 'publicVenueCatalog') && str_contains($index_js, 'idx-catalog-card-rate') && str_contains($index_js, 'idx-modal-rate') && str_contains($index_js, 'hotelRateText') && str_contains($index_js, 'Rate on request'),
    'homepage categories use a responsive stacked carousel sequence' => str_contains($index_php, 'idx-catalog-stack') && !str_contains($index_php, 'idx-catalog-grid') && substr_count($index_php, 'class="idx-catalog-section idx-catalog-section--') === 1 && str_contains($index_php, "['Event Hall' => 'Event Halls', 'Resort Villa' => 'Resort Villas', 'Hotel Room' => 'Hotel Rooms']") && str_contains($index_css, '.idx-catalog-stack { display: flex; flex-direction: column;') && !str_contains($index_css, '.idx-catalog-stack { display: grid') && !str_contains($index_css, '.idx-catalog-stack { grid-template-columns') && str_contains($index_css, '.idx-catalog-card { flex: 0 0 100%; display: grid;') && str_contains($index_js, 'Object.values(venue.facts || {}).slice(0, 3)'),
    'carousel controls use accessible icons, overlay positions, and one-item disable state' => str_contains($index_php, 'fa-chevron-left') && str_contains($index_php, 'fa-chevron-right') && str_contains($index_php, 'class="idx-carousel-prev" aria-label="Previous <?php echo htmlspecialchars($label); ?>"') && str_contains($index_php, 'class="idx-carousel-next" aria-label="Next <?php echo htmlspecialchars($label); ?>"') && str_contains($index_php, 'idx-carousel-position') && str_contains($index_js, 'control.disabled = cards.length <= 1') && str_contains($index_js, 'idx-catalog-shell-empty'),
    'modal calendar legend names rendered availability states safely' => str_contains($index_php, 'idx-modal-calendar-legend') && str_contains($index_php, '>Available</span>') && str_contains($index_php, '>Selected</span>') && str_contains($index_php, '>Unavailable</span>') && str_contains($index_php, 'data-calendar-legend="checkout-boundary" hidden') && str_contains($index_php, 'aria-hidden="true"') && str_contains($index_js, 'checkoutBoundaryLegend.hidden = venue.category !== \'Hotel Room\'') && str_contains($index_css, '.idx-modal-calendar .idx-modal-calendar-legend') && str_contains($index_css, '.idx-modal-calendar-legend-dot--checkout') && str_contains($index_css, '.idx-modal-calendar-legend-dot--unavailable { background: #e06666;'),
    'modal gallery contains thumbnail overflow without scrollbar chrome' => str_contains($index_css, '.idx-modal-gallery { position: relative; min-width: 0;') && str_contains($index_css, 'overflow: hidden; background: var(--idx-ink)') && str_contains($index_css, 'overflow-x: auto; overflow-y: hidden; overscroll-behavior-x: contain') && str_contains($index_css, 'scrollbar-width: none') && str_contains($index_css, '.idx-modal-thumbnails::-webkit-scrollbar') && str_contains($index_js, "scrollIntoView({ inline: 'nearest', block: 'nearest' })"),
    'mobile modal clears the fixed header with a safe bounded layer' => str_contains($index_css, 'z-index: 2000') && str_contains($index_css, '--idx-mobile-header-offset: calc(72px + env(safe-area-inset-top, 0px))') && str_contains($index_css, 'align-items: start; justify-items: center') && str_contains($index_css, 'padding: calc(var(--idx-mobile-header-offset) + 1rem) 1rem 1rem') && str_contains($index_css, 'max-height: calc(100svh - var(--idx-mobile-header-offset) - 2rem)'),
    'single venue carousels remove dead controls and keep many-item navigation' => str_contains($index_js, "shell.classList.toggle('idx-catalog-shell-single', isSingle)") && str_contains($index_js, "section.dataset.carouselState = isSingle ? 'single' : 'multi'") && str_contains($index_css, '.idx-catalog-shell-single { padding-bottom: 0; }') && str_contains($index_css, '.idx-carousel-controls[hidden] { display: none; }') && str_contains($index_css, 'idx-catalog-shell:not(.idx-catalog-shell-single):not(.idx-catalog-shell-empty)'),
    'villa detail action wins later important outline overrides' => str_contains($ui_refinement_css, '.idx-page .idx-catalog-section--resort-villa .idx-catalog-card-actions .idx-btn-outline-dark') && str_contains($ui_refinement_css, 'color: var(--idx-paper) !important') && str_contains($ui_refinement_css, 'color: var(--idx-ink) !important'),
    'venue rows stay compact with a layered villa image treatment' => str_contains($index_css, 'height: clamp(18rem, 28vw, 19rem)') && str_contains($index_css, 'grid-template-columns: minmax(0, .82fr) minmax(0, 1.18fr)') && str_contains($index_css, 'background: transparent; box-shadow: none') && str_contains($index_css, 'top: -3.25rem') === false && str_contains($index_css, 'left: -3.25rem'),
    'homepage rows retain editorial spacing and usable carousel controls' => str_contains($index_css, '.idx-catalog-heading::after') && str_contains($index_css, 'top: clamp(9rem, 14vw, 11rem)') && str_contains($index_css, 'min-height: 44px') && str_contains($index_css, 'font-variant-numeric: tabular-nums') && str_contains($index_css, '.idx-catalog-section--resort-villa .idx-carousel-controls button'),
    'modal is framed, viewport bounded, and mobile scroll fallback remains' => str_contains($index_css, 'width: min(78rem, 100%)') && str_contains($index_css, 'grid-template-columns: minmax(0, 1.2fr) minmax(0, .8fr)') && str_contains($index_css, 'height: min(84svh, 44rem)') && str_contains($index_css, 'max-height: min(84svh, calc(100svh - 2rem))') && str_contains($index_css, 'overflow: hidden') && str_contains($index_css, 'overflow-y: auto; overscroll-behavior: contain') && str_contains($index_css, 'max-height: calc(100svh - var(--idx-mobile-header-offset) - 2rem); overflow: auto') && str_contains($index_css, '@media (max-height: 640px) and (min-width: 768px)') && !str_contains($index_js, 'const rateFacts'),
    'homepage featured reviews use a separate endpoint and safe DOM rendering' => !str_contains($index_php, 'top_rated_venues') && !str_contains($index_php, 'publicTopRatedVenues') && str_contains($index_php, 'What guests are saying') && str_contains($index_php, 'idx-review-viewport') && str_contains($index_php, 'idx-review-track') && str_contains($top_rated_render_body, 'get_featured_reviews.php') && str_contains($top_rated_render_body, 'renderFeaturedReviews') && str_contains($top_rated_render_body, 'toPublicReview') && str_contains($top_rated_render_body, 'idx-testimonial-card') && str_contains($top_rated_render_body, 'replaceChildren') && str_contains($top_rated_render_body, '.textContent') && str_contains($top_rated_render_body, 'slice(0, 12)') && !str_contains($top_rated_render_body, 'innerHTML'),
    'featured reviews keep contrast, responsive cards, and empty or failed states contained' => str_contains($index_css, '.idx-top-rated { background: var(--idx-sand)') && str_contains($index_css, '.idx-top-rated-head {') && str_contains($index_css, '.idx-testimonial-card') && str_contains($index_css, '.idx-testimonial-quote') && str_contains($index_css, '.idx-review-viewport') && str_contains($index_css, '.idx-review-track') && str_contains($index_css, '.idx-review-controls[hidden]') && str_contains($index_css, '.idx-top-rated[hidden]') && str_contains($top_rated_render_body, 'topRatedSection.hidden = true') && str_contains($top_rated_render_body, 'catch(() => renderFeaturedReviews([]))') && str_contains($top_rated_render_body, 'reviewer') && str_contains($top_rated_render_body, 'textContent') && !str_contains($top_rated_render_body, 'innerHTML'),
    'featured review endpoint and modal endpoint remain separate contracts' => str_contains($featured_reviews_php, "LIMIT 50") && str_contains($featured_reviews_php, "'review_key' =>") && str_contains($index_js, 'get_featured_reviews.php') && str_contains($index_js, 'get_venue_reviews.php'),
    'featured review carousel uses 3, 2, and 1 visible cards with finite controls' => str_contains($index_js, 'window.innerWidth > 1024 ? 3') && str_contains($index_js, 'window.innerWidth >= 768 ? 2') && str_contains($index_js, 'Math.ceil(reviewCarouselState.cards.length / reviewCarouselState.visible)') && str_contains($index_js, 'reviewPrev.disabled = reviewCarouselState.page === 0') && str_contains($index_js, 'reviewNext.disabled = reviewCarouselState.page >= reviewCarouselState.pageCount - 1') && str_contains($index_js, 'aria-current') && str_contains($index_js, 'swipeThreshold = 56') && str_contains($index_js, 'priorFirstVisible') && str_contains($index_js, "event.key === 'ArrowLeft'") && str_contains($index_js, "event.key === 'ArrowRight'"),
    'featured review carousel has no autoplay and supports fallback images and reduced motion' => !str_contains($index_js, 'setInterval') && str_contains($index_js, 'setReviewImageFallback') && str_contains($index_js, 'placeholderImage') && str_contains($index_css, '@media (prefers-reduced-motion: reduce)') && str_contains($index_css, '.idx-review-track'),
    'homepage modal fixes body and restores exact scroll and inline styles' => str_contains($index_js, 'document.documentElement') && str_contains($index_js, 'scrollLock.y = window.scrollY') && str_contains($index_js, 'body.style.paddingRight') && str_contains($index_js, 'scrollLock.bodyPosition') && str_contains($index_js, 'scrollLock.bodyTop') && str_contains($index_js, 'scrollLock.bodyWidth') && str_contains($index_js, "body.style.position = 'fixed'") && str_contains($index_js, 'body.style.position = scrollLock.bodyPosition') && str_contains($index_js, 'body.style.top = `-${scrollLock.y}px`') && str_contains($index_js, 'body.style.top = scrollLock.bodyTop') && str_contains($index_js, "body.style.width = '100%'") && str_contains($index_js, 'body.style.width = scrollLock.bodyWidth') && str_contains($index_js, 'window.scrollTo({left: 0, top: scrollLock.y') && str_contains($index_css, 'overscroll-behavior: contain'),
    'modal arrows and calendar navigation use accessible icon buttons' => str_contains($index_php, 'fa-xmark') && substr_count($index_php, 'fa-chevron-left') >= 2 && substr_count($index_php, 'fa-chevron-right') >= 2 && str_contains($index_php, 'aria-label="Previous image"') && str_contains($index_php, 'aria-label="Next month"'),
    'summary labels render the xss fixture as text' => str_contains($xss_fixture, '<img src=x onerror=alert(1)>') && str_contains($booking_js, 'labelEl.textContent = label') && str_contains($booking_js, 'breakdownEl.replaceChildren()') && !str_contains($booking_js, '<span>${label}') && !str_contains($booking_js, 'summary.html'),
    'calendar ignores stale availability and supports keyboard cells' => str_contains($calendar_js, 'availabilityRequestGeneration') && str_contains($calendar_js, 'requestGeneration') && str_contains($calendar_js, 'if (requestGeneration !== this.availabilityRequestGeneration) return;') && str_contains($calendar_js, 'createElement(isInteractive ? "button" : "div")') && str_contains($calendar_js, 'isPastDate'),
    'calendar selection normalizes local dates before rendering' => str_contains($calendar_js, 'function normalizeCalendarDate(value)') && str_contains($calendar_js, '/^(\d{4})-(\d{2})-(\d{2})$/') && str_contains($calendar_js, 'new Date(year, month - 1, day)') && str_contains($calendar_js, 'localDate.getFullYear() !== year') && str_contains($calendar_js, 'localDate.setHours(0, 0, 0, 0)') && str_contains($calendar_js, 'this.endDate = normalizedStart ? normalizeCalendarDate(endDate) : null') && is_file($calendar_timezone_test),
    'lock dates rejects noncanonical and past starts before insert' => str_contains($lock_dates_php, "preg_match('/\\A[0-9]{4}-[0-9]{2}-[0-9]{2}\\z/D'") && str_contains($lock_dates_php, "format('Y-m-d') === \$start_date") && str_contains($lock_dates_php, "new DateTimeImmutable('today')") && str_contains($lock_dates_php, '$start_dt < $today') && str_contains($lock_dates_php, 'begin_transaction'),
    'homepage delegates document closing to footer' => !str_contains($index_php, '</body>') && !str_contains($index_php, '</html>'),
    'post-auth destination is allowlisted' => str_contains($booking_intent_php, "BOOKING_AUTH_DESTINATION = 'booking_resume'") && str_contains($booking_intent_php, 'hash_equals'),
    'resume requires a one-time server marker, not a query alone' => str_contains($booking_intent_php, "BOOKING_AUTH_RESUME_MARKER = 'booking_resume_marker'") && str_contains($booking_intent_php, '$_SESSION[BOOKING_AUTH_RESUME_MARKER] = true;') && str_contains($booking_intent_php, 'function booking_auth_consume_resume_marker(): bool') && str_contains($booking_intent_php, 'unset($_SESSION[BOOKING_AUTH_RESUME_MARKER]);') && str_contains($booking_php, '$booking_resume_marker = booking_auth_consume_resume_marker();') && str_contains($booking_php, '$booking_resume = isset($_GET[\'resume\']) && $_GET[\'resume\'] === \'1\'') && str_contains($booking_php, "'resume' => \$booking_resume"),
    'invalid or post-setup lock success releases the fresh hold' => $lock_method_start !== false && str_contains(substr($booking_js, $lock_method_start), 'let serverLockCreated = false;') && str_contains(substr($booking_js, $lock_method_start), 'serverLockCreated = true;') && str_contains(substr($booking_js, $lock_method_start), "fetch('actions/bookings/unlock_dates.php'") && str_contains(substr($booking_js, $lock_method_start), "The server did not return a valid hold expiry."),
    'admin override cancellation path is retired' => !preg_match('/force' . '.?' . 'cancel/i', $admin_status_php . $read('includes/admin-page/admin_bookings.php') . $read('assets/js/admin-page/admin_bookings.js')) && str_contains($admin_status_php, "throw new Exception('Invalid action provided.')"),
    'ordinary admin cancellation only accepts pending bookings' => $cancel_position !== false && str_contains($cancel_body, "locked_booking['booking_status'] ?? '') !== 'Pending'") && str_contains($cancel_body, 'Only Pending bookings can be declined or cancelled.'),
    'showroom receptionist exposes an accessible skippable dialog' => str_contains($showroom_php, 'id="showroom-receptionist"') && str_contains($showroom_php, 'role="dialog"') && str_contains($showroom_php, 'aria-modal="true"') && str_contains($showroom_php, 'aria-labelledby="receptionist-title"') && str_contains($showroom_php, 'aria-describedby="receptionist-message"') && str_contains($showroom_php, 'data-receptionist-skip') && str_contains($showroom_php, 'id="receptionist-reopen"'),
    'showroom receptionist includes the approved intent flow hooks' => str_contains($showroom_php, 'data-receptionist-intent="Event Hall"') && str_contains($showroom_php, 'data-receptionist-intent="Hotel Room"') && str_contains($showroom_php, 'data-receptionist-intent="Resort Villa"') && str_contains($showroom_php, 'data-receptionist-close') && str_contains($showroom_js, 'mediaVenues') && str_contains($showroom_js, 'rankVenues') && str_contains($showroom_js, 'data-receptionist-answer') && str_contains($showroom_js, 'pano_urls') && str_contains($showroom_js, 'room.gallery'),
    'showroom receptionist exposes deterministic raw ranking data' => str_contains($showroom_php, "'capacity_value' => \$capacity_value") && str_contains($showroom_php, "'rate_value' => \$rate_value") && str_contains($showroom_php, "'beds_value' => \$beds_value") && str_contains($showroom_js, 'room.capacity_value') && str_contains($showroom_js, 'room.rate_value') && str_contains($showroom_js, 'room.beds_value'),
    'showroom receptionist query admits available venues only' => str_contains($showroom_php, "WHERE v.status = 'Available'") && !str_contains($showroom_php, "WHERE v.status != 'Inactive'") && !str_contains($showroom_php, "WHERE v.status = 'Active'"),
    'showroom receptionist keeps nullable numbers absent and ranks ties deterministically' => str_contains($showroom_js, 'value === null || value === undefined') && str_contains($showroom_js, 'value.trim() === ""') && str_contains($showroom_js, 'leftTitle !== rightTitle') && str_contains($showroom_js, 'leftId !== rightId') && str_contains($showroom_js, 'leftVenueId !== rightVenueId') && str_contains($showroom_php, 'ORDER BY v.id ASC, hr.room_type ASC'),
    'showroom receptionist resets hints and recovers image or focus state' => str_contains($showroom_js, 'hintPending = false') && str_contains($showroom_js, 'hintReadyRoomId = null') && str_contains($showroom_js, 'const transitionImage') && str_contains($showroom_js, 'candidateIndex + 1 < candidates.length') && str_contains($showroom_js, 'disableGuideFocus') && str_contains($showroom_js, 'restoreGuideFocus'),
    'showroom receptionist uses cinematic scene and media-specific actions' => str_contains($showroom_php, 'receptionist-backdrop-image') && str_contains($showroom_js, 'Start 360° tour') && str_contains($showroom_js, 'Explore photos') && str_contains($showroom_js, 'data-receptionist-photo-prev') && str_contains($showroom_js, 'data-receptionist-photo-next') && str_contains($showroom_js, 'receptionist-photo-counter') && str_contains($showroom_css, 'showroom-receptionist-backdrop') && str_contains($showroom_css, 'body.showroom-receptionist-open .showroom-container'),
    'showroom receptionist caps exact matches and bounds explicit all view' => str_contains($showroom_js, 'const selectVenues') && str_contains($showroom_js, 'slice(0, 3)') && str_contains($showroom_js, 'data-receptionist-view-all') && str_contains($showroom_js, 'data-receptionist-all-prev') && str_contains($showroom_js, 'data-receptionist-all-next') && str_contains($showroom_js, 'pageSize = 3'),
    'showroom receptionist preserves answer navigation and real response states' => str_contains($showroom_js, 'data-receptionist-menu') && str_contains($showroom_js, 'data-receptionist-compare') && str_contains($showroom_js, 'data-receptionist-change-search') && str_contains($showroom_js, 'const renderResponse') && str_contains($showroom_js, 'Back to venue') && str_contains($showroom_js, 'These inclusions are listed for this venue'),
    'showroom receptionist filters premium matches to explicit room labels' => str_contains($showroom_js, 'item.exactFit && (preference !== "premium" || item.vip)') && str_contains($showroom_js, 'No Premium / VIP match') && str_contains($showroom_js, 'Change preference') && !str_contains($showroom_js, 'preference === "premium" && !hasExplicitPremium'),
    'showroom receptionist locks document roots and keeps panorama sharp fallback' => str_contains($showroom_js, 'document.documentElement.classList.add("showroom-receptionist-open")') && str_contains($showroom_js, 'document.documentElement.classList.remove("showroom-receptionist-open")') && str_contains($showroom_js, 'const panoramaImages') && str_contains($showroom_js, 'room.pano_urls') && str_contains($showroom_js, 'room.pano_url') && str_contains($showroom_js, 'const venueImages') && str_contains($showroom_css, 'html.showroom-receptionist-open'),
    'showroom receptionist why response names saved request naturally' => str_contains($showroom_js, 'const preferenceLabel') && str_contains($showroom_js, 'accommodates everyone') && str_contains($showroom_js, 'extra guest place') && !str_contains($showroom_js, 'guests of room'),
    'showroom receptionist keeps why evidence preference-specific' => str_contains($showroom_js, 'matchingHotelRoomsByRate') && str_contains($showroom_js, 'preference === "value"') && str_contains($showroom_js, 'preference === "space"') && str_contains($showroom_js, 'explicitly identifies Premium/VIP') && !str_contains($showroom_js, 'matchingHotelRooms()'),
    'showroom receptionist paginates complete inclusions without scroll clipping' => str_contains($showroom_js, 'includedPage') && str_contains($showroom_js, 'data-receptionist-included-prev') && str_contains($showroom_js, 'data-receptionist-included-next') && str_contains($showroom_js, 'pageSize = 6') && str_contains($showroom_css, '.receptionist-response-list') && str_contains($showroom_css, 'max-height: none') && str_contains($showroom_css, 'overflow: visible'),
    'showroom receptionist restores view-all comparison context' => str_contains($showroom_js, 'selectionOrigin') && str_contains($showroom_js, 'selectedAllPage') && str_contains($showroom_js, 'data-receptionist-list-origin') && str_contains($showroom_js, 'renderAllPage()') && str_contains($showroom_js, 'Compare venues'),
    'showroom receptionist focuses modal before staged choices reveal' => str_contains($showroom_js, 'const focusGuideDialog') && str_contains($showroom_js, 'focusGuideDialog();') && str_contains($showroom_js, 'classList.contains("is-entering")') && str_contains($showroom_js, 'focusable.filter(element => element === receptionistSkip)'),
    'showroom receptionist entrance supports staged and reduced motion states' => str_contains($showroom_css, '.showroom-receptionist.is-entering') && str_contains($showroom_css, 'clip-path: inset(0 100% 0 0)') && str_contains($showroom_css, '.showroom-receptionist.is-ready::before') && str_contains($showroom_css, 'opacity: 0;') && str_contains($showroom_js, 'prefers-reduced-motion') && str_contains($showroom_js, 'entranceDuration'),
    'showroom receptionist keeps long content reachable in one contained scroller' => str_contains($showroom_css, '.receptionist-panel') && str_contains($showroom_css, 'overflow: hidden') && str_contains($showroom_css, '.receptionist-choices') && str_contains($showroom_css, 'overflow-y: auto') && str_contains($showroom_js, 'receptionistChoices.scrollTop = 0'),
    'showroom receptionist keeps announcements hidden and scroll position stable' => str_contains($showroom_css, '.receptionist-live') && str_contains($showroom_css, 'clip-path: inset(50%)') && str_contains($showroom_js, 'receptionistPanel.scrollTop = 0') && str_contains($showroom_js, 'preventScroll: true'),
    'showroom receptionist fallbacks remain category-safe and borderless' => str_contains($showroom_php, 'category_fallback') && !str_contains($showroom_php, 'Experience ultimate luxury') && !str_contains($showroom_css, '.showroom-receptionist-dialog::after'),
    'showroom receptionist builds dynamic facts as safe DOM text' => str_contains($showroom_js, 'receptionistChoices.replaceChildren') && str_contains($showroom_js, 'document.createElement("dl")') && str_contains($showroom_js, 'detail.textContent = value') && str_contains($showroom_js, 'button.textContent = label') && !str_contains($showroom_js, 'receptionistChoices.innerHTML'),
    'showroom dropdown and receptionist share venue activation' => substr_count($showroom_js, 'function activateVenue(roomId)') === 1 && str_contains($showroom_js, 'activateVenue(this.getAttribute("data-room"))') && str_contains($showroom_js, 'activateVenue(room.id)') && str_contains($showroom_js, 'activateVenue(targetItem.getAttribute("data-room"))'),
    'showroom receptionist reuses the venue booking contract' => str_contains($showroom_js, 'function getBookingUrl(room)') && str_contains($showroom_js, 'venue_id: String(room.venue_id)') && str_contains($showroom_js, 'category: String(room.category || "")') && str_contains($showroom_js, 'room_type: String(room.room_type || "")') && str_contains($showroom_js, 'venue_name: String(room.venue_name || "")') && str_contains($showroom_js, 'bookLink.href = getBookingUrl(room, guideContext.startDate, guideContext.endDate)') && str_contains($showroom_js, 'params.set("start_date"') && str_contains($showroom_js, 'params.set("end_date"'),
    'showroom receptionist asks category-specific dates with canonical local validation' => str_contains($showroom_js, 'eventDate') && str_contains($showroom_js, 'checkInDate') && str_contains($showroom_js, 'visitDate') && str_contains($showroom_js, 'Choose date later') && str_contains($showroom_js, 'const dateStepFor') && str_contains($showroom_js, 'const isCanonicalDate') && str_contains($showroom_js, 'value >= todayLocal()') && str_contains($showroom_js, 'addLocalDays(startDate, 1)') && str_contains($showroom_js, 'const createDateQuestion') && str_contains($showroom_js, 'receptionist-calendar-day') && str_contains($showroom_js, 'event.key === "PageUp"') && str_contains($showroom_css, '.receptionist-calendar-day') && str_contains($showroom_css, '.receptionist-calendar-nav') && str_contains($showroom_css, 'padding-top: max(5rem, calc(env(safe-area-inset-top) + 3.5rem))') && str_contains($showroom_css, 'day and month controls retain their 44px touch targets'),
    'showroom receptionist checks current availability before ranking without claiming a hold' => str_contains($showroom_js, 'actions/bookings/get_room_availability.php') && str_contains($showroom_js, 'actions/bookings/fetch_dates.php') && str_contains($showroom_js, 'building_name') && str_contains($showroom_js, 'Promise.allSettled') && str_contains($showroom_js, 'guideState.availabilityConfirmedIds') && str_contains($showroom_js, 'availabilityStatus === "confirmed"') && str_contains($showroom_js, 'No hold was created'),
    'showroom receptionist recovers date errors and no-result availability' => str_contains($showroom_js, 'const renderAvailabilityError') && str_contains($showroom_js, 'const renderNoAvailability') && str_contains($showroom_js, 'Retry') && str_contains($showroom_js, 'View without date') && str_contains($showroom_js, 'Change date'),
    'showroom receptionist uses progressive venue actions and compact response back' => str_contains($showroom_js, 'More details') && str_contains($showroom_js, 'Change search') && str_contains($showroom_js, 'Back to venue') && str_contains($showroom_css, '.receptionist-back-text') && str_contains($showroom_js, 'Compare rooms') && str_contains($showroom_js, 'Compare venues'),
    'showroom receptionist uses square sharp media and grounded arrival composition' => str_contains($showroom_css, 'aspect-ratio: 1 / 1') && str_contains($showroom_js, 'fa-chevron-left') && str_contains($showroom_js, 'fa-chevron-right') && str_contains($showroom_css, 'inset: 0 auto 0 0') && str_contains($showroom_css, '.showroom-receptionist::before') && str_contains($showroom_css, 'clip-path: inset(0 100% 0 0)'),
    'showroom receptionist explains checked local dates without a hold claim' => str_contains($showroom_js, 'const formatLocalDate') && str_contains($showroom_js, 'const availabilityDateSummary') && str_contains($showroom_js, 'Availability checked for') && str_contains($showroom_js, 'no hold was created') && str_contains($showroom_js, 'guideContext.endDate'),
    'showroom receptionist aligns dialogue beside the host and bounds compact controls' => str_contains($showroom_css, '.showroom-receptionist:not(.is-venue-state) .receptionist-panel') && str_contains($showroom_css, 'justify-content: flex-start') && str_contains($showroom_css, 'padding-left: clamp(18rem, 36vw, 36rem)') && str_contains($showroom_css, '.receptionist-sharp-image .receptionist-photo-controls') && str_contains($showroom_css, 'inset: 0;') && str_contains($showroom_css, 'border-radius: 50%') && str_contains($showroom_css, '.receptionist-back-text') && str_contains($showroom_css, 'width: max-content') && str_contains($showroom_css, '.showroom-receptionist.is-venue-state .receptionist-panel-head > div') && str_contains($showroom_css, 'overflow-wrap: normal') && str_contains($showroom_css, 'word-break: normal'),
    'showroom review keys and safe responsive review states are wired' => str_contains($showroom_php, "'review_key'") && str_contains($showroom_php, "'hotel-' . md5") && str_contains($showroom_php, "'event-'") && str_contains($showroom_php, "'villa-'") && str_contains($showroom_php, 'showroom-reviews-mobile') && str_contains($showroom_js, 'get_venue_reviews.php') && str_contains($showroom_js, 'reviewCache') && str_contains($showroom_js, 'textContent') && str_contains($showroom_css, '.showroom-review-state-error'),
    'public support keeps CMS content in a compact responsive information layout' => str_contains($support_php, 'support-anchor-nav') && str_contains($support_php, 'support_contact_heading') && str_contains($support_php, 'support_faq_json') && str_contains($support_php, 'retired_policy_hash') && !preg_match('/force' . '.?' . 'cancel/i', $support_php) && str_contains($support_css, 'grid-template-columns: repeat(2') && str_contains($support_css, 'grid-template-columns: 1fr'),
    'showroom receptionist ships responsive focus and reduced-motion states' => str_contains($showroom_css, '.showroom-receptionist.is-open') && str_contains($showroom_css, '.receptionist-reopen') && str_contains($showroom_css, '@media (max-width: 700px)') && str_contains($showroom_css, '@media (prefers-reduced-motion: reduce)') && str_contains($showroom_js, 'event.key === "Escape"') && str_contains($showroom_js, 'event.key !== "Tab"'),
    'showroom receptionist supports dialogue continuation, sound, and venue handoff' => str_contains($showroom_php, 'data-receptionist-continue') && str_contains($showroom_php, 'data-receptionist-sound-toggle') && str_contains($showroom_php, 'receptionist-ambience.wav') && str_contains($showroom_php, 'receptionist-reopen-face') && str_contains($showroom_js, 'setChoicesGated') && str_contains($showroom_js, 'revealDialogueChoices') && str_contains($showroom_js, 'receptionist-handoff-clone') && str_contains($showroom_js, 'startVenueHandoff') && str_contains($showroom_js, 'visibilitychange') && str_contains($showroom_css, '.receptionist-handoff-clone') && str_contains($showroom_css, '.receptionist-continue'),
    'showroom receptionist keeps mobile utilities and calendar targets separated' => str_contains($showroom_js, 'More details') && str_contains($showroom_css, 'top: max(.75rem, env(safe-area-inset-top))') && str_contains($showroom_css, 'bottom: calc(max(1.25rem, env(safe-area-inset-bottom)) + 4.3rem)') && str_contains($showroom_css, 'bottom: calc(8.2rem + env(safe-area-inset-bottom))') && str_contains($showroom_css, '.receptionist-calendar-day { min-width: 2.75rem; min-height: 2.75rem;') && str_contains($showroom_css, '.receptionist-calendar-nav { min-width: 2.75rem; min-height: 2.75rem;') && str_contains($showroom_css, 'Keep the venue title below the fixed Sound and Skip utilities.') && str_contains($showroom_css, 'Keep the date heading clear of the fixed Sound and Skip utilities.'),
    'showroom receptionist gates only welcome and auto-resolves follow-up dialogue' => str_contains($showroom_js, 'dialogueRequiresContinue') && str_contains($showroom_js, 'requireContinue: isInitialGreeting') && str_contains($showroom_js, 'requireContinue: true') && str_contains($showroom_js, '}, 780)') && str_contains($showroom_js, 'data-dialogue-pending') && str_contains($showroom_css, 'opacity: 0 !important') && str_contains($showroom_css, 'visibility: hidden') && str_contains($showroom_css, 'transition: none !important') && str_contains($showroom_css, 'receptionist-choice-resolve') && str_contains($showroom_css, 'clip-path 780ms') && str_contains($showroom_js, 'fadeAmbienceTo(0.3)') && str_contains($showroom_css, 'object-position: 50% 0') && str_contains($showroom_css, 'transform: none;') && str_contains($showroom_css, 'inset: 2rem 0 auto') && str_contains($showroom_css, 'height: 56svh'),
];

$failed = 0;
foreach ($checks as $label => $passed) {
    echo ($passed ? "PASS" : "FAIL") . "|$label\n";
    if (!$passed) $failed++;
}
exit($failed === 0 ? 0 : 1);
